// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2eTZK3FmJboDR_Nne6HG9dpXvez_Be5s',
    appId: '1:825150779373:web:2fe17072e45859a43081e4',
    messagingSenderId: '825150779373',
    projectId: 'shiinex-app',
    authDomain: 'shiinex-app.firebaseapp.com',
    storageBucket: 'shiinex-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAY5RhwAcbiRx33UqiyGmO2d152PrluUQ',
    appId: '1:825150779373:android:e516d6aaf59ae3023081e4',
    messagingSenderId: '825150779373',
    projectId: 'shiinex-app',
    storageBucket: 'shiinex-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN-qwTR0fJ8wgdeOrPG0121cm-29M7rHM',
    appId: '1:825150779373:ios:ade5c9ba599dccf13081e4',
    messagingSenderId: '825150779373',
    projectId: 'shiinex-app',
    storageBucket: 'shiinex-app.firebasestorage.app',
    iosBundleId: 'com.example.shinex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN-qwTR0fJ8wgdeOrPG0121cm-29M7rHM',
    appId: '1:825150779373:ios:ade5c9ba599dccf13081e4',
    messagingSenderId: '825150779373',
    projectId: 'shiinex-app',
    storageBucket: 'shiinex-app.firebasestorage.app',
    iosBundleId: 'com.example.shinex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2eTZK3FmJboDR_Nne6HG9dpXvez_Be5s',
    appId: '1:825150779373:web:dbb221427b926a633081e4',
    messagingSenderId: '825150779373',
    projectId: 'shiinex-app',
    authDomain: 'shiinex-app.firebaseapp.com',
    storageBucket: 'shiinex-app.firebasestorage.app',
  );
}
